apiVersion: v1
items:
- apiVersion: v1
  data:
    POSTGRES_DB: ZWx0ZV9mZWxob19rb255dmVr
    POSTGRES_PASSWORD: cGV0aXlldGk=
    POSTGRES_USER: cGV0aXlldGk=
  kind: Secret
  metadata:
    creationTimestamp: "2024-03-18T09:01:58Z"
    name: donttellanyone
    namespace: default
    resourceVersion: "21215"
    uid: 429fa66f-2b4f-4164-b653-c243db826006
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
