version: "3.8"
services:
  # without docker-compose, host will be `localhost`
  # with docker-compose
  # host will be whatever name you give to the postgres service
  # so host will be `db`
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - library-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5342"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    depends_on:
      - db
    image: library-api-slim
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "7676:7676"
    expose:
      - 7676
volumes:
  library-db-volume:
