apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: google/cloud-sdk:alpine
            args: [ "apk --update add postgresql", "pg_dump -u elte_felho_konyvter > db-$(date +%s).bak", "gsutil cp db.bak gs://myblog/backups" ]
            envFrom:
            - secretRef:
                  name: donttellanyone
            - configMapRef:
                  name: my-configmap
            volumeMounts:
            - name: postgres-database-storage
              mountPath: /var/lib/postgresql/data
          volumes: 
          - name: postgres-database-storage
            persistentVolumeClaim:
              claimName: postgres-pv-claim
          restartPolicy: OnFailure
