apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-daemonset
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: library-slim-api:k8s
        ports:
        - containerPort: 7676
